export type Service = {
  slug: string;
  title: string;
  short: string;
  intro: string;
  items: string[];
  group: string;
  number: string;
};
export type Project = {
  id: string;
  slug: string;
  title: string;
  client: string;
  category: string;
  image: string;
  year: string;
  summary: string;
  need: string;
  solution: string;
  before: string;
  after: string;
  gallery: string[];
  videoUrl: string;
  demo: boolean;
  published: boolean;
};
export type Article = {
  id: string;
  slug: string;
  title: string;
  category: string;
  summary: string;
  body: string;
  image: string;
  date: string;
  seoTitle: string;
  seoDescription: string;
  published: boolean;
};
export type Settings = {
  name: string;
  tagline: string;
  description: string;
  phone: string;
  whatsapp: string;
  email: string;
  instagram: string;
  address: string;
  hours: string;
  mapUrl: string;
  siteUrl: string;
  gaId: string;
  pixelId: string;
  searchConsoleId: string;
  showreelUrl: string;
  about: string;
  team: string;
  clients: { name: string; logo: string }[];
  testimonials: { name: string; company: string; text: string }[];
};
export type Content = {
  settings: Settings;
  services: Service[];
  projects: Project[];
  articles: Article[];
};
export type Lead = {
  id: string;
  company: string;
  name: string;
  phone: string;
  email: string;
  services: string[];
  budget: string;
  startDate: string;
  message: string;
  fileName: string;
  filePath: string;
  fileType: string;
  createdAt: string;
  status: string;
};
